'use server';

import { detectUnusedCode } from '@/ai/flows/unused-code-detection';
import { generateDetailedReport } from '@/ai/flows/detailed-optimization-reports';
import type { AnalysisResult } from '@/lib/types';

export async function analyzeUrl(url: string): Promise<AnalysisResult> {
    try {
        if (!url.startsWith('http://') && !url.startsWith('https://')) {
            url = `https://${url}`;
        }
        // Validate URL format
        new URL(url);

        const mockCoverageData = "This is placeholder coverage data. In a real scenario, this would be generated by a tool like Puppeteer's coverage API.";

        const [unusedCodeResult, detailedReportResult] = await Promise.all([
            detectUnusedCode({ url, coverageData: mockCoverageData }),
            generateDetailedReport({ url, coverageData: mockCoverageData })
        ]);

        // Mocking other metrics as we can't run Lighthouse in this environment
        const performanceScore = Math.floor(Math.random() * 41) + 60; // 60-100
        const lcp = `${(Math.random() * 1.5 + 1).toFixed(1)}s`;
        const cls = `${(Math.random() * 0.15).toFixed(2)}`;
        const tbt = `${Math.floor(Math.random() * 200 + 50)}ms`;

        return {
            performanceScore,
            webVitals: { lcp, cls, tbt },
            unusedCode: unusedCodeResult,
            detailedReport: detailedReportResult,
            url: url
        };
    } catch (error) {
        console.error("Analysis failed:", error);

        if (error instanceof TypeError) {
             throw new Error("Invalid URL. Please enter a valid URL format (e.g., example.com).");
        }

        throw new Error("Failed to analyze the URL. The AI model may be overloaded. Please try again later.");
    }
}
